"""add request table

Revision ID: ad7b774fbc30
Revises: 39b827b12608
Create Date: 2026-04-21 10:27:43.112621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7b774fbc30'
down_revision = '39b827b12608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(length=140), nullable=False),
    sa.Column('direct', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_request_timestamp'))

    op.drop_table('request')
    # ### end Alembic commands ###
